figarodefault: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  pool: 5
  username: root
  password: 123456
  socket: /var/run/mysqld/mysqld.sock
  redis:
    host: localhost
    port: 6379
    db: 0
    options:
      namespace: blog-dev

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

staging:
  <<: *default
  database: blog_staging

production:
  <<: *default
  database: blog_production
  username: blog
  password: <%= ENV["blog_DATABASE_PASSWORD"] %>
